services:
  postgres:
    image: postgres:17.5-alpine
    container_name: storage-postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PUBLIC_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 30

  minio:
    image: minio/minio:latest
    container_name: storage-minio
    restart: unless-stopped
    env_file: ./.env
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
    # ВАЖНО: наружу порты не публикуем — доступ только через nginx
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 30

  # создаёт бакеты и (опционально) делает public бакет доступным на чтение
  minio-init:
    image: minio/mc:latest
    container_name: storage-minio-init
    depends_on:
      minio:
        condition: service_healthy
    env_file: ./.env
    entrypoint: ["/bin/sh", "-c"]
    command: ["sh /init/init.sh"]
    volumes:
      - ./minio/init:/init:ro
    restart: "no"

  # NGINX reverse proxy (80/443 наружу)
  nginx:
    image: nginx:alpine
    container_name: storage-nginx
    restart: unless-stopped
    depends_on:
      - minio
    ports:
      - "80:80"
      - "443:443"
    env_file: ./.env
    volumes:
      - ./nginx/conf.d:/etc/nginx/templates:ro
      - ./nginx/www:/var/www/certbot
      - ./certbot:/etc/letsencrypt
    command: >
      /bin/sh -c "
      envsubst '$$S3_DOMAIN' < /etc/nginx/templates/s3.conf > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'
      "

  # Certbot контейнер (сертификаты и renew)
  certbot:
    image: certbot/certbot:latest
    container_name: storage-certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do sleep 12h & wait $$!; done"
