services:
  postgres:
    image: postgres:17.5-alpine
    container_name: storage-postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PUBLIC_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 30


  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: storage-minio
    restart: unless-stopped
    env_file: ./.env
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
    ports:
      - "${MINIO_PUBLIC_API_PORT}:9000"
      - "${MINIO_PUBLIC_CONSOLE_PORT}:9001"
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 30

  # создаёт бакеты и (опционально) делает public бакет доступным на чтение
  minio-init:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: storage-minio-init
    depends_on:
      minio:
        condition: service_healthy
    env_file: ./.env
    entrypoint: ["/bin/sh", "-c"]
    command: ["sh /init/init.sh"]
    volumes:
      - ./minio/init:/init:ro
    restart: "no"

