services:
  postgres:
    image: postgres:17.5-alpine
    container_name: storage-postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PUBLIC_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 30

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: storage-minio
    restart: unless-stopped
    env_file: ./.env
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 30

  minio-init:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: storage-minio-init
    depends_on:
      minio:
        condition: service_healthy
    env_file: ./.env
    entrypoint: ["/bin/sh", "-c"]
    command: ["sh /init/init.sh"]
    volumes:
      - ./minio/init:/init:ro
    restart: "no"

  nginx-dev:
    image: nginx:1.27-alpine
    container_name: storage-nginx-dev
    restart: unless-stopped
    depends_on:
      - minio
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/www:/var/www/certbot
      - ./certbot:/etc/letsencrypt
    profiles: ["dev"]

  nginx:
    image: nginx:1.27-alpine
    container_name: storage-nginx
    restart: unless-stopped
    depends_on:
      - minio
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/www:/var/www/certbot
      - ./certbot:/etc/letsencrypt
    profiles: ["prod"]

  certbot:
    image: certbot/certbot:v2.11.0
    container_name: storage-certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: /bin/sh
    command: -c "trap exit TERM; while :; do sleep 12h & wait $$!; done"
